#!/bin/bash

# START
set -e

## UNINSTALL
rm -rf /lib/firefox-developer/firefox /usr/bin/firefox-developer
# Only delete the desktop file if it will be replaced
rm -f ~/.local/share/applications/firefox-developer.desktop

# DOWNLOAD
curl -L -o firefox-developer.tar.bz2 https://download.mozilla.org/\?product\=firefox-devedition-latest-ssl\&os\=linux64\&lang\=en-US

# EXTRACT
tar -xf firefox-developer.tar.bz2
rm -rf firefox-developer.tar.bz2
mv firefox firefox-developer

# INSTALL
sudo mv firefox-developer /lib
sudo ln -s /lib/firefox-developer/firefox /usr/bin/firefox-developer

# ICON
ln -s /lib/firefox-developer/browser/chrome/icons/default/default128.png ~/.local/share/icons/hicolor/128x128/apps/firefox-developer.png
update-desktop-database ~/.local/share/icons

# GNOME INTEGRATION
echo -e "[Desktop Entry]\nEncoding=UTF-8\nName=Firefox Developer\nComment=Firefox Developer Edition\nExec=firefox-developer\nIcon=firefox-developer\nStartupWMClass=Firefox Developer\nType=Application\nCategories=Internet;\n" >> ~/.local/share/applications/firefox-developer.desktop

# NOTIFY
echo "Installed!"
